### ISSUE TITLE
Ansible-lint

### ISSUE THREAD

**Issue by javajon** [willhallonline/docker-ansible#1]
Consider adding ansible-lint?

`pip install ansible-lint`

[Exampled here.](https://github.com/haxorof/docker-ansible-lint)

-------

Somewhat like the alias ["cansible"](https://github.com/javajon/bashful/blob/master/ansible-from-containers.sh)  ;-)

Thanks Will!

**Comment by willhallonline** [comment]
You are possibly right that I could add it in. I will look at completing in the next couple of weeks and then close this issue. Thanks for bringing to my attention... Do you know if it does YAML linting too?

**Comment by willhallonline** [comment]
Added this to all builds and make jump to Ansible 2.8 too.
