### ISSUE TITLE
ssh path, ".ssh" missing in mount option

### ISSUE THREAD

**Issue by bartdorlandt** [willhallonline/docker-ansible#14]
in the mount and inject command example the .ssh portion is missing (on the right side of the ":").

**Comment by willhallonline** [comment]
Hey @bartdorlandt. I am not sure as this matters? Basically speaking there is only the root user inside the container, so it will make that if it doesn't already exist? I could make a .ssh directory? Would that resolve the issue?

**Comment by willhallonline** [comment]
You are totally right by the way with regards to the issue.

**Comment by bartdorlandt** [comment]
PR done. cheers.
