### ISSUE TITLE
mitogen path in ubuntu 18.04

### ISSUE THREAD

**Issue by Lusitaniae** [willhallonline/docker-ansible#16]
At least for ubuntu 18.04 the path mitogen is installed is
`/usr/local/lib/python2.7/dist-packages/ansible_mitogen/plugins/strategy`

Instead of the documented 

`/usr/lib/python2.7/site-packages/ansible_mitogen/plugins/strategy`

This is just a note. 

If you plan to move everything to python 3 soon, I guess no need for action here.

**Comment by willhallonline** [comment]
I might need to update. At the moment I am trying to get an opinion as to how/if to support Python 2. You would just suggest dropping, or running totally separate set of container tags?

**Comment by Lusitaniae** [comment]
Good question.

Personally I'd go for python 3 only, but not sure how many people relying on your images and python2

**Comment by willhallonline** [comment]
I am not sure either 🤷‍♂ . The container is just about to hit 2M pulls on Docker hub and I know that some of the previous organisations I have worked for have used it at one point or another inside CI. However, from LinkedIn (which I am also trying to garner understanding) it seems that there is little support for Python2.
