### ISSUE TITLE
WORKDIR /ansible in the Dockerfile

### ISSUE THREAD

**Issue by eill** [willhallonline/docker-ansible#2]
Hello, William!

The documentation for your image recommends mounting playbook directory to the /ansible path, but the workdir in the docker image is set to the /, so to execute playbook we need to call "ansible-playbook /ansible/playbook.yml".

Unfortunately, ansible looks for config files into $(pwd) and predefined config dirs, and thus we need explicitly mount all the configuration files (like ansible.cfg) to the /etc/ansible or other default search directories. What do you think about changing WORKDIR in the Dockerfiles to the /ansible?

I think it may be useful, but I'm not sure how it would affect the existing pipelines, so I'm not submitting a PR yet.

**Comment by willhallonline** [comment]
Hey Timur. This, I guess depends on the structure of your projects. I normally have an ./ansible directory inside projects so I can keep other things in the project, however, it may make more sense to do it from the local directory that you are in. I will look at changing it, I don't believe that it should make that much impact on others.

**Comment by willhallonline** [comment]
I should also add. Thanks for raising the issue and contributing. 😄 👍
