### ISSUE TITLE
json_query filter needs jmespath installed

### ISSUE THREAD

**Issue by mgerhardy** [willhallonline/docker-ansible#24]
See https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter

Would be cool to get an pip install for jmespath as part of the image.

**Comment by willhallonline** [comment]
I have a look and my initial feeling was "No, I don't really want to add this" but actually on reflection I think it would be pretty small and I may end up using it myself, especially as I am using some CMDB work that may be as json (Terraform/Terraform Cloud).

I will add it then close the issue.

**Comment by willhallonline** [comment]
Added with new release v2.4
