### ISSUE TITLE
Some tags are missing

### ISSUE THREAD

**Issue by regzon** [willhallonline/docker-ansible#31]
Hello. The docs state that tags `2.10-alpine`, `2.10-buster` and `2.10-stretch` exist. But when I tried to fetch them using the command (applicable to every listed tag):  
```
docker pull willhallonline/ansible:2.10-alpine
```

I've got  the error:  
```
Error response from daemon: manifest for willhallonline/ansible:2.10-alpine not found: manifest unknown: manifest unknown
```

The "tags" page on the Docker Hub shows that those tags don't exist, too.

There's either a problem in the documentation or some misconfiguration.

Btw, thank you for your repository!

**Comment by regzon** [comment]
Also, I found that the tag `latest` doesn't correspond to the tag `2.10-alpine-3.11`.

Output of docker image list:
```
willhallonline/ansible         2.10-alpine-3.11   9f03c121d12d   3 weeks ago     450MB
willhallonline/ansible         latest             90bb5aa1e604   5 months ago    387MB
```

**Comment by willhallonline** [comment]
You are absolutely right. There has been some issue. I will look to resolve it in the next couple of days. Thanks for letting me know. I also need to prune out all of the tags that are insecure (old libraries, insecure OS) basically so no-one can use them any more.

Thanks again.

**Comment by willhallonline** [comment]
This is all of the tags and ones to keep and remove:

Remove:
- 2.5
- 2.5-alpine
- 2.5-alpine-3
- 2.5-alpine-3.6
- 2.5-alpine-3.7
- 2.5-alpine-3.8
- 2.5-alpine-3.9
- 2.5-centos
- 2.5-centos-7
- 2.5-ubuntu
- 2.5-ubuntu-16.04
- 2.5-ubuntu-18.04
- 2.7
- 2.7-alpine
- 2.7-alpine-3
- 2.7-alpine-3.6
- 2.7-alpine-3.7
- 2.7-alpine-3.8
- 2.7-alpine-3.9
- 2.7-centos
- 2.7-centos-7
- 2.7-stretch
- 2.7-stretch-slim
- 2.7-ubuntu
- 2.7-ubuntu-16.04
- 2.7-ubuntu-18.04
- 2.8-alpine-3.8
- 2.8-alpine-3.9
- alpine-3.6
- alpine-3.7
- alpine-3.8

Keep:
- 2.8
- 2.8-alpine
- 2.8-alpine-3.10
- 2.8-buster
- 2.8-buster-slim
- 2.8-centos
- 2.8-centos-7
- 2.8-stretch
- 2.8-stretch-slim
- 2.8-ubuntu
- 2.8-ubuntu-16.04
- 2.8-ubuntu-18.04
- 2.8-ubuntu-20.04
- 2.9-alpine
- 2.9-buster
- 2.9-buster-slim
- 2.9-centos
- 2.9-stretch
- 2.9-ubuntu
- 2.9-ubuntu-16.04
- 2.9-ubuntu-20.04
- 2.10-alpine-3.10
- 2.10-alpine-3.11
- 2.10-centos-7
- 2.10-ubuntu-16.04
- 2.10-ubuntu-18.04
- 2.10-ubuntu-20.04
- alpine
- alpine-3
- buster
- buster-slim
- centos
- centos-7
- debian
- latest
- ubuntu
- ubuntu-16.04
- ubuntu-18.04
