### ISSUE TITLE
Mitogen version

### ISSUE THREAD

**Issue by DougDavenport** [willhallonline/docker-ansible#34]
Greetings,

Running ansible-playbook with willhallonline/ansible:alpine is giving the following:

> ERROR! Your Ansible version (2.10.1) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 9).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.

also:

> ansible --version
ansible 2.10.1
  config file = /eis-ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.2 (default, Jul 18 2020, 19:35:03) [GCC 9.2.0]

is showing 2.10.1 and docs say it should be 2.10.3

Am I doing something wrong?

Thanks!

**Comment by willhallonline** [comment]
Hi @DougDavenport, I am struggling to keep the docs up with the correct version of Ansible that is running. It is out of date again now: running 2.10.9, 2.9.21 and 2.8.20. The docs should be up to date, but actually managing it is another thing.

With regards to Mitogen, I think that there are some issues with 2.10, however, it is expected to work at some point. The changelog notes that support for Ansible 2.10 is likely to arrive in Mitogen v0.3.0 (https://mitogen.networkgenomics.com/changelog.html) and this is the issue that you can follow to see how that is going (https://github.com/mitogen-hq/mitogen/issues/731).

I would suggest that at the moment, use one of the 2.9 releases if you need Mitogen support and use 2.10 if you don't. I am probably not going to change it as I would expect that it will come along soon enough that to remove and then re-add is not worth the time.
