### ISSUE TITLE
Docker command in LABEL

### ISSUE THREAD

**Issue by thokari** [willhallonline/docker-ansible#36]
https://github.com/willhallonline/docker-ansible/blob/53a8ebe8caa329962d7288cd3104014e38f12885/ansible210/alpine311/Dockerfile#L14

I just noticed this, shouldn't this say `ansible:2.10` ?

**Comment by willhallonline** [comment]
Yes, a lot of the labels are a bit out of date. I am not sure that anyone actually uses them. I'll try to check and update them soon. I'll leave the issue open until its resolved.

**Comment by willhallonline** [comment]
I have fixed all of these (at least I think I have) closing issue for now.
