### ISSUE TITLE
Add the possibility to set ansible minor version

### ISSUE THREAD

**Issue by meons** [willhallonline/docker-ansible#39]
It would be nice to add the possibility to set ansible minor version.

For example for ansible 2.10 and based on ansible [doc](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#selecting-an-ansible-artifact-and-version-to-install), something like that could be implemented:

```
...
# set ansible version
ENV ANSIBLE_VERSION 2.10.4
...
RUN pip3 install "ansible-base==${ANSIBLE_VERSION}"
...
```

The key point is to replace ansible by ansible-base (see referenced doc above), otherwise the latest minor version (currently 2.10.13) will always be installed whatever you set in the line `pip3 install ansible==2.10.7 && \`.

What do you think?

**Comment by willhallonline** [comment]
I should do this... I haven't done it yet, so I'll leave this issue here for when I do get round to it. Thanks for contributing.

**Comment by willhallonline** [comment]
You know when you ask about something and then you get around to it eventually... Well, this is done now. Thanks again to @meons for making the issue.
