### ISSUE TITLE
Install "ansible" collection (pip package)

### ISSUE THREAD

**Issue by goetzc** [willhallonline/docker-ansible#40]
Since Ansible was split into `ansible-core` and collections, the `ansible` package now contains useful set of collections which were available before the spit. This is needed _specially_ since version _2.11_.

https://pypi.org/project/ansible/

These are the collections included in the `ansible` package:
https://galaxy.ansible.com/ansible

Included utilities are:
-  netcommon 
- network
- posix
-  security 
- utils
- windows
- workshops

**Comment by willhallonline** [comment]
I have added this for the most recent versions. Thanks for bringing it to my attention, I was still using 2.10 for most things, but will probably move to 2.11 now.

**Comment by willhallonline** [comment]
Resolved by v3.1.2

**Comment by goetzc** [comment]
I see it https://github.com/willhallonline/docker-ansible/commit/ac4e4889c08514c53691414a35bdbd36bdac3cf9. Thanks!
