### ISSUE TITLE
Wrong ansible versions in the ubuntu- and alpine- based ansible-2.11 images

### ISSUE THREAD

**Issue by vitalyrepin** [willhallonline/docker-ansible#47]
It looks like that ansible-2.11 is not available in any of the ubuntu- and alpine-based images. Ansible 2.13.0 is included into these images.

For example:

docker run --rm willhallonline/ansible:2.11-alpine-3.14 ansible --version
ansible [core 2.13.0]

docker run --rm willhallonline/ansible:2.11-ubuntu-20.04 ansible --version
ansible [core 2.13.0]

docker run --rm willhallonline/ansible:2.11-alpine-3.15 ansible --version
 ansible [core 2.13.0]

**Comment by pavelpikta** [comment]
```
docker run -it willhallonline/ansible:2.11-alpine-3.13 /bin/sh
/ansible # ansible --version
ansible [core 2.13.0]
config file = None
configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.10/site-packages/ansible
ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
executable location = /usr/bin/ansible
python version = 3.10.4 (main, Apr 30 2022, 16:49:16) [GCC 11.2.1 20220219]
jinja version = 3.1.2
libyaml = False
/ansible # cat /etc/alpine-release
3.16.0
/ansible #
````
@willhallonline  looks like a problem with build specific docker image

**Comment by willhallonline** [comment]
So, this has been an issue with dependencies, wherein it is installing 2.11.11 (as an example) but by also installing the wider ansible-lint project it upgrades other versions due to dependencies, so I will need to tie the versions together. Should be fixed later today.
