### ISSUE TITLE
ERROR! Invalid play strategy specified: mitogen_linear when using ansible-base/alpine316/Dockerfile

### ISSUE THREAD

**Issue by lirany1** [willhallonline/docker-ansible#55]
When using:
https://github.com/willhallonline/docker-ansible/blob/master/ansible-base/alpine316/Dockerfile

it's give me an error:
ERROR! Invalid play strategy specified: mitogen_linear

**Comment by willhallonline** [comment]
At the moment there are conflicts betweent he `ansible-core` version being 2.13 and `ansible` version being > 5. So, either you would need to use ansible < 6. https://github.com/mitogen-hq/mitogen/issues/929

However, if it is just that it can't find mitogen as a tool then it may be that it is being stored in a different location. (probably that the python version is different. Within 2.13-alpine-3.16 it is `/usr/lib/python3.10/site-packages/ansible_mitogen/plugins`.

**Comment by lirany1** [comment]
Thanks :)  seems like related to https://github.com/mitogen-hq/mitogen/issues/929

**Comment by willhallonline** [comment]
Closing as can't easily fix. Issue is with mitogen.
