### ISSUE TITLE
New architecture for image with latest tag on Docker Hub

### ISSUE THREAD

**Issue by mjsd** [willhallonline/docker-ansible#63]
Thank you for providing a greate image. We experienced some problems after todays update of the docker image on Docker Hub. The processor architecture for the image with latest tag changed from amd64 to arm64. Was this by perpose or was it just a misstake. Should I update my scripts to use som other tag from now?

Best regards
// Mattias Johansson

**Comment by wkleinhenz** [comment]
I'm running into this issue as well, I was using the Alpine image tag but it appears that this tag now points to the same container hash as the ARM tag which as stated above using arm64 rather than amd64

**Comment by willhallonline** [comment]
I am sorry about that. `alpine` and `latest` are both built from the same thing. You should have both linux/arm64 and linux/amd64 available for both. 

![image](https://user-images.githubusercontent.com/1371070/236201205-b0a8ff78-da4b-48ca-9b59-eebee4ae3e9a.png)

It works for me, but I guess not for everyone?

**Comment by eliasfrigard** [comment]
Caused issues for us as well this morning, so we switched to an older, named version that worked.

**Comment by mjsd** [comment]
I also switced to an older named version but now it looks ok. The latest tag has both architectures. I guess it was some delay :)

**Comment by willhallonline** [comment]
In theory, the docker daemon should pick the one that **your** architecture is. If not, you can request which one `--platform linux/arm64` or `--platform linux/amd64`. I mainly put out the staticly named tags as they are much less likely to change than `latest` (which gets rebuilt on every CI run). I honestly do not know why, it stopped working as I didn't replace the `latest` with _only_ arm image. It worries me a bit. :/

**Comment by willhallonline** [comment]
I'm going to close this as I think it is resolved. Please re-open (or preferable start a new issue) if the issue re-appears (I will try not to make that happen).
