### ISSUE TITLE
ansible-galaxy collection list is rather old

### ISSUE THREAD

**Issue by gnotari** [willhallonline/docker-ansible#64]
Many of the collections included are really old (possibly years old, in some cases).
I second the decision of including them, but updated collections should be included at some point.

And yes, of course, I can install them by hand, but the whole point of having a packaged ansible distro is dispensing with most of that..

**Comment by willhallonline** [comment]
That is fine. Do you want to give me some guidance of where/what would be an improvement? For where I use the container it is fine as mainly use it to run Ansible via CI jobs rather than as a local machine utility.

**Comment by willhallonline** [comment]
@gnotari , did you ever have an update for this? I am not sure that there is anything I can do for ansible-galaxy but just wanted to make sure I was not missing something.

**Comment by willhallonline** [comment]
Closing as no updates.
