### ISSUE TITLE
ansible-galaxy requires resolvelib<0.9.0,>=0.5.3

### ISSUE THREAD

**Issue by jaydrogers** [willhallonline/docker-ansible#72]
## Background
I absolutely love the effort you put into this project, thank you! I am using this project on [another open source project ](https://github.com/serversideup/spin/pull/24) and I'm running into issues when using the latest alpine version.

## Affected images
- willhallonline/ansible:**latest**
- willhallonline/ansible:**alpine**

### Special Notes
> [!NOTE]
> This does not happen on willhallonline/ansible:**ubuntu**

## Steps to reproduce
Run a container:
```bash
docker run --rm --pull always -it willhallonline/ansible:alpine sh
```
Once in the container, try to run an Ansible Galaxy install:
```bash
ansible-galaxy collection install geerlingguy.mac
```

## Expected Results
- I am expecting my Ansible Galaxy collection to install and succeed

## Actual Results

<img width="1002" alt="image" src="https://github.com/willhallonline/docker-ansible/assets/3174134/6852fa28-4f4b-4056-bb73-3e81b5719a65">

#### Text version of error
```bash
/ansible # ansible-galaxy collection install geerlingguy.mac
Starting galaxy collection install process
Process install dependency map
ERROR! ansible-galaxy requires resolvelib<0.9.0,>=0.5.3
```
## Possibly related issues
- https://github.com/willhallonline/docker-ansible/issues/62

**Comment by jaydrogers** [comment]
Just adding an update, this confusion could all be from the "latest" and "alpine" tags being tagged on the **2.13** release.

2.13 went End Of Life this November.

https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html
![Screenshot 2023-12-20 at 08 37 07@2x](https://github.com/willhallonline/docker-ansible/assets/3174134/89c0866d-d662-4f8e-9963-04de5d919658)

### Workaround
I started using `willhallonline/ansible:2.15-alpine-3.18` and this error message went away. 👍

**Comment by jaydrogers** [comment]
Sweet, thanks! Let me know if you ever need any help. I can submit PRs to help reduce your workload.

I maintain these Docker images (https://serversideup.net/open-source/docker-php/), but I specifically use your images for deploying our open source project called "Spin": https://serversideup.net/open-source/spin/docs/getting-started/how-spin-works

Thanks for all your hard work!

**Comment by willhallonline** [comment]
@jaydrogers thanks for the offer. Happy to take on PRs, I have tried to make it as easy as possible to manage as I don't have a lot of time to make significant changes.

Closing issue as believe that this is resolved with version updates.
