### ISSUE TITLE
Possibly wrong ssh key path in example commands

### ISSUE THREAD

**Issue by EdyTheCow** [willhallonline/docker-ansible#76]
I've been testing this image using the example commands provided in the readme here https://github.com/willhallonline/docker-ansible?tab=readme-ov-file#mount-local-directory-and-ssh-key 

I noticed this path to private key may be wrong `~/.ssh/id_rsa:/root/id_rsa`, the aliases examples use `~/.ssh/id_rsa:/root/.ssh/id_rsa` which include the dir `.ssh`. Not sure if this is done on purpose or if it's a mistake.

**Comment by willhallonline** [comment]
I think this is just an example for if your current user (whose directory is denoted by ~) is using both a `.ssh` directory inside their user and linking it to the root user (probably the user in the container). I would suggest that you make this appropriate to you. In fact, from a personal level I'm not using rsa keys any more, but realise that when I did this it was the industry standard.
